# base image
FROM node:lts-alpine AS build-stage

# set working directory
WORKDIR ./

# copy package.json and package-lock.json
COPY package*.json ./

# install dependencies
RUN npm install --production

# copy project files and folders to the working directory
COPY . .

# build the project
RUN npm run build



# production stage

FROM nginx:stable-alpine AS production-stage

# 베포파일 이동
COPY --from=build-stage ./dist /usr/share/nginx/html

# Copy Nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

# expose port 80
EXPOSE 80

# start the application
CMD [ "nginx", "-g", "daemon off;" ]

